//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.24 at 10:01:57 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.primaresearch.org/PAGE/gts/pagecontent/2017-07-15", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.kit.pagexml;
