//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.24 at 10:01:57 AM CEST 
//


package edu.kit.pagexml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RolesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RolesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TableCellRole" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2017-07-15}TableCellRoleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RolesType", propOrder = {
    "tableCellRole"
})
public class RolesType {

    @XmlElement(name = "TableCellRole")
    protected TableCellRoleType tableCellRole;

    /**
     * Gets the value of the tableCellRole property.
     * 
     * @return
     *     possible object is
     *     {@link TableCellRoleType }
     *     
     */
    public TableCellRoleType getTableCellRole() {
        return tableCellRole;
    }

    /**
     * Sets the value of the tableCellRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableCellRoleType }
     *     
     */
    public void setTableCellRole(TableCellRoleType value) {
        this.tableCellRole = value;
    }

}
