//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.24 at 10:01:57 AM CEST 
//


package edu.kit.pagexml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupTypeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GroupTypeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="paragraph"/>
 *     &lt;enumeration value="list"/>
 *     &lt;enumeration value="list-item"/>
 *     &lt;enumeration value="figure"/>
 *     &lt;enumeration value="article"/>
 *     &lt;enumeration value="div"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GroupTypeSimpleType")
@XmlEnum
public enum GroupTypeSimpleType {

    @XmlEnumValue("paragraph")
    PARAGRAPH("paragraph"),
    @XmlEnumValue("list")
    LIST("list"),
    @XmlEnumValue("list-item")
    LIST_ITEM("list-item"),
    @XmlEnumValue("figure")
    FIGURE("figure"),
    @XmlEnumValue("article")
    ARTICLE("article"),
    @XmlEnumValue("div")
    DIV("div"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    GroupTypeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GroupTypeSimpleType fromValue(String v) {
        for (GroupTypeSimpleType c: GroupTypeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
